# Generated by Django 4.2 on 2023-05-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birim', models.CharField(choices=[('kilogram', 'Kilogram'), ('adet', 'Adet'), ('sandık', 'Sandık'), ('kutu', 'Kutu'), ('demet', 'Demet')], max_length=20)),
                ('kategori', models.CharField(choices=[('meyve', 'Meyve'), ('sebze', 'Sebze'), ('ithal', 'İthal Ürünler')], max_length=20)),
            ],
        ),
    ]
