# Generated by Django 4.2.1 on 2023-05-06 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='birim',
            field=models.CharField(choices=[('Kilogram', 'Kilogram'), ('Adet', 'Adet'), ('Sandık', 'Sandık'), ('Kutu', 'Kutu'), ('Demet', 'Demet')], max_length=20),
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analiz.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
