# Generated by Django 4.2.1 on 2023-05-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0002_alter_product_birim_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_name', models.CharField(max_length=200)),
                ('marketplace_addres', models.CharField(max_length=300)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('day', models.CharField(choices=[('Pazartesi', 'Pazartesi'), ('Salı', 'Salı'), ('Çarşamba', 'Çarşamba'), ('Perşembe', 'Perşembe'), ('Cuma', 'Cuma'), ('Cumartesi', 'Cumartesi'), ('Pazar', 'Pazar')], max_length=20)),
            ],
        ),
    ]
