# Generated by Django 4.2.1 on 2023-05-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0004_placeofsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeofsale',
            name='products',
            field=models.ManyToManyField(to='analiz.sell'),
        ),
    ]
