# Generated by Django 4.2.1 on 2023-05-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0008_remove_placeofsale_date_placeofsale_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciro', models.IntegerField()),
                ('date', models.DateField()),
                ('place_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analiz.placeofsale')),
            ],
        ),
    ]
