# Generated by Django 4.2.1 on 2023-05-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0009_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='ciro',
            field=models.FloatField(),
        ),
    ]
