# Generated by Django 4.2.1 on 2023-05-07 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0011_productprofit_revenue_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprofit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analiz.sell'),
        ),
    ]
