# Generated by Django 4.2 on 2023-05-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0012_alter_productprofit_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprofit',
            name='unit_sales',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
